param(
    [string]$VersionFilePath
)

[xml]$VersionFile = Get-Content $VersionFilePath;
$Version = $VersionFile.Project.PropertyGroup | ? {$_.Version} | Select-Object -ExpandProperty Version;
$Prerelease = $VersionFile.Project.PropertyGroup | ? {$_.LastUpdated} | Select-Object -ExpandProperty LastUpdated;

if ($Version.Contains("-")) {
    $Version = $Version.Split("-")[0];
}
if ($Version.Contains("+")) {
    $Version = $Version.Split("+")[0];
}

$Prerelease = [Math]::Truncate(([DateTime]::Now - [DateTime]::Parse($Prerelease)).TotalDays * 10);

$fileContents = @"
//
// This code was generated by a tool. Any changes made manually will be lost the next time this code is regenerated.
//

using System.Resources;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System;

// General Information about an assembly is controlled through the following set of attributes. Change these attribute
// values to modify the information associated with an assembly.
[assembly: AssemblyDescription("A collection of tools I have found useful across more than one C# project.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("UnlimitedInf")]
[assembly: AssemblyCopyright("Copyright © UnlimitedInf (Tom Postler) 2016-{0}")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible to COM components. If you need to access a
// type in this assembly from COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]

[assembly: NeutralResourcesLanguage("en")]
[assembly: InternalsVisibleTo("Unlimitedinf.Tools.UnitTests")]

[assembly: AssemblyVersion("{1}.{2}")]
"@ -f [DateTime]::Now.Year, $Version, $Prerelease;

$fileContents > "$PSScriptRoot\AssemblyInfo.cs"
