//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unlimitedinf.Fileserve.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unlimitedinf.Fileserve.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File id not found..
        /// </summary>
        internal static string ErrorFileIdNotFound {
            get {
                return ResourceManager.GetString("ErrorFileIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        internal static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not sure what you wanted..
        /// </summary>
        internal static string ErrorIdk {
            get {
                return ResourceManager.GetString("ErrorIdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id not found..
        /// </summary>
        internal static string ErrorIdNotFound {
            get {
                return ResourceManager.GetString("ErrorIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of arguments for {0} module: {1}.
        /// </summary>
        internal static string ErrorIncorrectArgCount {
            get {
                return ResourceManager.GetString("ErrorIncorrectArgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command: {0}.
        /// </summary>
        internal static string ErrorInvalidCommand {
            get {
                return ResourceManager.GetString("ErrorInvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filename: {0}.
        /// </summary>
        internal static string ErrorInvalidFilename {
            get {
                return ResourceManager.GetString("ErrorInvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id: {0}.
        /// </summary>
        internal static string ErrorInvalidId {
            get {
                return ResourceManager.GetString("ErrorInvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid submodule: {0}.
        /// </summary>
        internal static string ErrorInvalidSubmodule {
            get {
                return ResourceManager.GetString("ErrorInvalidSubmodule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid uint: {0}.
        /// </summary>
        internal static string ErrorInvalidUint {
            get {
                return ResourceManager.GetString("ErrorInvalidUint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid web path: {0}.
        /// </summary>
        internal static string ErrorInvalidWebPath {
            get {
                return ResourceManager.GetString("ErrorInvalidWebPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id not found..
        /// </summary>
        internal static string ErrorUserIddNotFound {
            get {
                return ResourceManager.GetString("ErrorUserIddNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute path:.
        /// </summary>
        internal static string GetAFileAbsPath {
            get {
                return ResourceManager.GetString("GetAFileAbsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id: .
        /// </summary>
        internal static string GetAId {
            get {
                return ResourceManager.GetString("GetAId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File id: .
        /// </summary>
        internal static string GetAIdFile {
            get {
                return ResourceManager.GetString("GetAIdFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User id: .
        /// </summary>
        internal static string GetAIdUser {
            get {
                return ResourceManager.GetString("GetAIdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b \b.
        /// </summary>
        internal static string GetAPasswordBackspace {
            get {
                return ResourceManager.GetString("GetAPasswordBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string GetAPasswordCoverChar {
            get {
                return ResourceManager.GetString("GetAPasswordCoverChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass: .
        /// </summary>
        internal static string GetAPasswordPass {
            get {
                return ResourceManager.GetString("GetAPasswordPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User: .
        /// </summary>
        internal static string GetAStringUser {
            get {
                return ResourceManager.GetString("GetAStringUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte rate per file limit (def: inf): .
        /// </summary>
        internal static string GetAUintByteRateLimitInf {
            get {
                return ResourceManager.GetString("GetAUintByteRateLimitInf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concurrent file limit (def: 1): .
        /// </summary>
        internal static string GetAUintConcurrentFileLimit1 {
            get {
                return ResourceManager.GetString("GetAUintConcurrentFileLimit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web path: /.
        /// </summary>
        internal static string GetAUriFileWebPath {
            get {
                return ResourceManager.GetString("GetAUriFileWebPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (y/N): .
        /// </summary>
        internal static string GetAYesNoPrompt {
            get {
                return ResourceManager.GetString("GetAYesNoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose?.
        /// </summary>
        internal static string GetAYesNoVerbose {
            get {
                return ResourceManager.GetString("GetAYesNoVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string GetAYesNoY {
            get {
                return ResourceManager.GetString("GetAYesNoY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not add a file to the configuration..
        /// </summary>
        internal static string ProgramConfigFileAddFail {
            get {
                return ResourceManager.GetString("ProgramConfigFileAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted from configuration:
        ///  Web path: /{0}
        ///  Abs path: {1}.
        /// </summary>
        internal static string ProgramConfigFileDel {
            get {
                return ResourceManager.GetString("ProgramConfigFileDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not delete a file from the configuration..
        /// </summary>
        internal static string ProgramConfigFileDelFail {
            get {
                return ResourceManager.GetString("ProgramConfigFileDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not edit a file in the configuration..
        /// </summary>
        internal static string ProgramConfigFileEditFail {
            get {
                return ResourceManager.GetString("ProgramConfigFileEditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///  /{1}
        ///  {2}.
        /// </summary>
        internal static string ProgramConfigFileList {
            get {
                return ResourceManager.GetString("ProgramConfigFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;--&gt; {1}.
        /// </summary>
        internal static string ProgramConfigLinkAdd {
            get {
                return ResourceManager.GetString("ProgramConfigLinkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not add a link to the configuration..
        /// </summary>
        internal static string ProgramConfigLinkAddFail {
            get {
                return ResourceManager.GetString("ProgramConfigLinkAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link deleted from configuration:
        ///  {0}  {1}
        ///  {2}  {3}.
        /// </summary>
        internal static string ProgramConfigLinkDel {
            get {
                return ResourceManager.GetString("ProgramConfigLinkDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not delete a link from the configuration..
        /// </summary>
        internal static string ProgramConfigLinkDelFail {
            get {
                return ResourceManager.GetString("ProgramConfigLinkDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}  {1}.
        /// </summary>
        internal static string ProgramConfigLinkListFile {
            get {
                return ResourceManager.GetString("ProgramConfigLinkListFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1}.
        /// </summary>
        internal static string ProgramConfigLinkListUser {
            get {
                return ResourceManager.GetString("ProgramConfigLinkListUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///  {1}
        ///  concurrency: {2}
        ///  rate limit:  {3}.
        /// </summary>
        internal static string ProgramConfigUserAdd {
            get {
                return ResourceManager.GetString("ProgramConfigUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not add an user to the configuration..
        /// </summary>
        internal static string ProgramConfigUserAddFail {
            get {
                return ResourceManager.GetString("ProgramConfigUserAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted from configuration: {0}.
        /// </summary>
        internal static string ProgramConfigUserDel {
            get {
                return ResourceManager.GetString("ProgramConfigUserDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not delete user from the configuration..
        /// </summary>
        internal static string ProgramConfigUserDelFail {
            get {
                return ResourceManager.GetString("ProgramConfigUserDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not edit an user in the configuration..
        /// </summary>
        internal static string ProgramConfigUserEditFail {
            get {
                return ResourceManager.GetString("ProgramConfigUserEditFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1}.
        /// </summary>
        internal static string ProgramConfigUserList {
            get {
                return ResourceManager.GetString("ProgramConfigUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///  {1}
        ///  concurrency: {2}
        ///  rate limit:  {3}.
        /// </summary>
        internal static string ProgramConfigUserListVerbose {
            get {
                return ResourceManager.GetString("ProgramConfigUserListVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: fileserve MODULE [SUBMODULE] [COMMAND] [ARGS]
        ///
        ///A complete utilty to manage and serve up binary files on a per-user basis using
        ///HTTP to enable the largest audience consumption.
        ///
        ///Usage is similar to git. Example:
        ///    fileserve config user add
        ///Will pop up the walkthrough to add a user to the configuration.
        ///
        ///    fileserve help config
        ///    fileserve help config this and that
        ///Will give you the help for the module config.
        ///
        ///Modules:
        ///  config        Adjust the configuration of the users, files, a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramHelp {
            get {
                return ResourceManager.GetString("ProgramHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIG MODULE
        ///
        ///Usage: fileserve config SUBMODULE COMMAND [FILENAME]
        ///
        ///This module is used to adjust the configuration of the users, files, and links
        ///available when running the program.
        ///
        ///The config module looks for a fileserve.json in the current directory, but may
        ///also have this file passed in to override the default search. If the passed in
        ///file exists, then the configuration is loaded. If the passed in file does not
        ///exist, then the configuration will be saved there.
        ///
        ///This author&apos;s recommendatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProgramHelpConfig {
            get {
                return ResourceManager.GetString("ProgramHelpConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon unlimitedinf {
            get {
                object obj = ResourceManager.GetObject("unlimitedinf", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
